import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";

import "./globals.css";

//모바일 input 확대 방지
export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

//글꼴 PretendardVariable.woff2를 사용
const pretendard = localFont({
    src: "../../public/fonts/PretendardVariable.woff2",
    display: "swap",
    weight: "45 920",
    variable: "--font-pretendard",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" className={`${pretendard.variable}`}>
            <body className={pretendard.className}>{children}</body>
        </html>
    );
}
